local _, L = ...;

-- Profession
L["PROFESSION"] = "Enchanting";
-- Left Menu
L["LEFT_TITLE"] = "All Bonuses";
L["LEFT_TOOLTIP"] = "Sort recipes by the bonus they provide.";
-- Names
L["LEFT_01_NAME"] = SPELL_STAT1_NAME;
L["LEFT_02_NAME"] = SPELL_STAT2_NAME;
L["LEFT_03_NAME"] = SPELL_STAT3_NAME;
L["LEFT_04_NAME"] = SPELL_STAT4_NAME;
L["LEFT_05_NAME"] = SPELL_STAT5_NAME;
L["LEFT_06_NAME"] = "Stats";
L["LEFT_07_NAME"] = HEALTH;
L["LEFT_08_NAME"] = MANA;
L["LEFT_09_NAME"] = STAT_ARMOR;
L["LEFT_10_NAME"] = RESISTANCE_LABEL;
L["LEFT_11_NAME"] = DAMAGE;
L["LEFT_12_NAME"] = STAT_SPELLPOWER;
L["LEFT_13_NAME"] = SHOW_COMBAT_HEALING_TEXT;
L["LEFT_14_NAME"] = SPECIAL;
L["LEFT_15_NAME"] = "Proc";
L["LEFT_16_NAME"] = SKILL;
L["LEFT_17_NAME"] = "Create Wand";
L["LEFT_18_NAME"] = "Create Rod";
L["LEFT_19_NAME"] = MISCELLANEOUS;
-- Filters
L["LEFT_01_FILTER"] = SPELL_STAT1_NAME;
L["LEFT_02_FILTER"] = SPELL_STAT2_NAME;
L["LEFT_03_FILTER"] = SPELL_STAT3_NAME;
L["LEFT_04_FILTER"] = SPELL_STAT4_NAME;
L["LEFT_05_FILTER"] = SPELL_STAT5_NAME;
L["LEFT_06_FILTER"] = "Stats";
L["LEFT_07_FILTER"] = HEALTH;
L["LEFT_08_FILTER"] = MANA;
L["LEFT_09_FILTER"] = "Protection;Defense";
L["LEFT_10_FILTER"] = RESISTANCE_LABEL;
L["LEFT_11_FILTER"] = "Impact;Striking";
L["LEFT_12_FILTER"] = STAT_SPELLPOWER..";spellpower;sunfire;soulfrost";
L["LEFT_13_FILTER"] = SHOW_COMBAT_HEALING_TEXT;
L["LEFT_14_FILTER"] = "slay";
L["LEFT_15_FILTER"] = "Absorption;Chill;Crusader;Fiery;Unholy";
L["LEFT_16_FILTER"] = "Herbalism;Mining;Skinning;Fishing;Riding Skill;Speed;Deflect;Haste";
L["LEFT_17_FILTER"] = "Wand";
L["LEFT_18_FILTER"] = "Rod";
L["LEFT_19_FILTER"] = "";
-- Right Menu
L["RIGHT_TITLE"] = "All Slots";
L["RIGHT_TOOLTIP"] = "Sort recipes by the slot they enchant.";
-- Names
L["RIGHT_01_NAME"] = CHESTSLOT;
L["RIGHT_02_NAME"] = FEETSLOT;
L["RIGHT_03_NAME"] = WRISTSLOT;
L["RIGHT_04_NAME"] = HANDSSLOT;
L["RIGHT_05_NAME"] = BACKSLOT;
L["RIGHT_06_NAME"] = ENCHSLOT_2HWEAPON;
L["RIGHT_07_NAME"] = ENCHSLOT_WEAPON;
L["RIGHT_08_NAME"] = SHIELDSLOT;
L["RIGHT_09_NAME"] = "Create Wand";
L["RIGHT_10_NAME"] = "Create Rod";
L["RIGHT_11_NAME"] = MISCELLANEOUS;
-- Filters
L["RIGHT_01_FILTER"] = CHESTSLOT;
L["RIGHT_02_FILTER"] = "Boots";
L["RIGHT_03_FILTER"] = "Bracer";
L["RIGHT_04_FILTER"] = "Gloves";
L["RIGHT_05_FILTER"] = "Cloak";
L["RIGHT_06_FILTER"] = ENCHSLOT_2HWEAPON;
L["RIGHT_07_FILTER"] = ENCHSLOT_WEAPON;
L["RIGHT_08_FILTER"] = SHIELDSLOT;
L["RIGHT_09_FILTER"] = "Wand";
L["RIGHT_10_FILTER"] = "Rod";
L["RIGHT_11_FILTER"] = "";

L["SELF_ENCH"] = "Self Ench";